### ISSUE TITLE
issue while building 

### ISSUE THREAD

**Issue by navneet-rathi** [flytreeleft/sonar-auth-keycloak-plugin#1]
rathi@keystone:~/sonar-auth-keycloak-plugin$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ---------< org.github.flytreeleft:sonar-auth-keycloak-plugin >----------
[INFO] Building Keycloak Authentication for SonarQube 0.1.0-SNAPSHOT
[INFO] ----------------------------[ sonar-plugin ]----------------------------
[WARNING] The POM for org.keycloak:keycloak-authz-client:jar:3.3.0.CR1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.keycloak:keycloak-adapter-core:jar:3.3.0.CR1-SNAPSHOT is missing, no dependency information available
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.676 s
[INFO] Finished at: 2020-03-09T11:37:40Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sonar-auth-keycloak-plugin: Could not resolve dependencies for project org.github.flytreeleft:sonar-auth-keycloak-plugin:sonar-plugin:0.1.0-SNAPSHOT: The following artifacts could not be resolved: org.keycloak:keycloak-authz-client:jar:3.3.0.CR1-SNAPSHOT, org.keycloak:keycloak-adapter-core:jar:3.3.0.CR1-SNAPSHOT: Could not find artifact org.keycloak:keycloak-authz-client:jar:3.3.0.CR1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by flytreeleft** [comment]
@navneet-rathi Please try to change the `<keycloak.version>` from `3.3.0.CR1-SNAPSHOT` to `4.5.0.Final` in the `pom.xml` and rebuild it again.

**Comment by flytreeleft** [comment]
@navneet-rathi The keycloak version has been upgraded, you can try it again with the latest commit 7c793fd.
